// Maps vehicle model names → car category
// Owner can extend this list; it's the single source of truth

const CAR_CATEGORY_MAP = {
  // Hatchback
  swift: "Hatchback",
  alto: "Hatchback",
  "alto k10": "Hatchback",
  wagonr: "Hatchback",
  "wagon r": "Hatchback",
  baleno: "Hatchback",
  i20: "Hatchback",
  i10: "Hatchback",
  "grand i10": "Hatchback",
  polo: "Hatchback",
  jazz: "Hatchback",
  glanza: "Hatchback",
  tiago: "Hatchback",
  altroz: "Hatchback",
  kwid: "Hatchback",
  santro: "Hatchback",
  celerio: "Hatchback",
  ignis: "Hatchback",
  brio: "Hatchback",
  beat: "Hatchback",
  spark: "Hatchback",
  micra: "Hatchback",
  ritz: "Hatchback",
  "a-star": "Hatchback",
  zen: "Hatchback",

  // Sedan
  dzire: "Sedan",
  "swift dzire": "Sedan",
  amaze: "Sedan",
  aura: "Sedan",
  tigor: "Sedan",
  xcent: "Sedan",
  aspire: "Sedan",
  city: "Sedan",
  verna: "Sedan",
  ciaz: "Sedan",
  rapid: "Sedan",
  yaris: "Sedan",
  sunny: "Sedan",
  linea: "Sedan",
  indigo: "Sedan",
  accent: "Sedan",
  etios: "Sedan",

  // Compact SUV
  brezza: "Compact SUV",
  "vitara brezza": "Compact SUV",
  "grand vitara": "Compact SUV",
  venue: "Compact SUV",
  sonet: "Compact SUV",
  nexon: "Compact SUV",
  punch: "Compact SUV",
  magnite: "Compact SUV",
  kiger: "Compact SUV",
  ecosport: "Compact SUV",
  freestyle: "Compact SUV",
  "urban cruiser": "Compact SUV",
  "urban cruiser hyryder": "Compact SUV",
  hyryder: "Compact SUV",
  fronx: "Compact SUV",

  // SUV
  creta: "SUV",
  seltos: "SUV",
  harrier: "SUV",
  safari: "SUV",
  xuv700: "SUV",
  "xuv 700": "SUV",
  scorpio: "SUV",
  "scorpio n": "SUV",
  "scorpio classic": "SUV",
  thar: "SUV",
  bolero: "SUV",
  "bolero neo": "SUV",
  compass: "SUV",
  meridian: "SUV",
  alcazar: "SUV",
  hector: "SUV",
  "hector plus": "SUV",
  kushaq: "SUV",
  slavia: "SUV",
  tiguan: "SUV",
  tucson: "SUV",
  duster: "SUV",
  captur: "SUV",
  ertiga: "SUV",

  fortuner: "SUV",
  endeavour: "SUV",
  everest: "SUV",
  gloster: "SUV",
  "cx-5": "SUV",
  "cx-8": "SUV",

  // MUV
  tavera: "MUV",
  xylo: "MUV",
  supro: "MUV",
  eeco: "MUV",
  omni: "MUV",
  lodgy: "MUV",
  triber: "MUV",
  marazzo: "MUV",
  xl6: "MUV",
  carens: "MUV",
  innova: "MUV",
  "innova crysta": "MUV",
  "innova hycross": "MUV",

  // Luxury
  "3 series": "Luxury",
  "5 series": "Luxury",
  "c class": "Luxury",
  "c-class": "Luxury",
  "e class": "Luxury",
  "e-class": "Luxury",
  a4: "Luxury",
  a6: "Luxury",
  q3: "Luxury",
  q5: "Luxury",
  xc40: "Luxury",
  xc60: "Luxury",
  xc90: "Luxury",
  x1: "Luxury",
  x3: "Luxury",
  x5: "Luxury",
  glc: "Luxury",
  gle: "Luxury",
  "volvo s60": "Luxury",
  "volvo s90": "Luxury",
  ct6: "Luxury",
  es: "Luxury",
  is: "Luxury",
  xf: "Luxury",
  xe: "Luxury",
  "f-pace": "Luxury",
  "e-pace": "Luxury",

  // Ultra Luxury
  "7 series": "Ultra Luxury",
  "s class": "Ultra Luxury",
  "s-class": "Ultra Luxury",
  "a-class": "Ultra Luxury",
  a8: "Ultra Luxury",
  q7: "Ultra Luxury",
  q8: "Ultra Luxury",
  x7: "Ultra Luxury",
  "range rover": "Ultra Luxury",
  "range rover sport": "Ultra Luxury",
  defender: "Ultra Luxury",
  "range rover velar": "Ultra Luxury",
  "landcruiser-300": "Ultra Luxury",

  discovery: "Ultra Luxury",
  bentayga: "Ultra Luxury",
  continental: "Ultra Luxury",
  phantom: "Ultra Luxury",
  ghost: "Ultra Luxury",
  cullinan: "Ultra Luxury",
  urus: "Ultra Luxury",
  cayenne: "Ultra Luxury",
  panamera: "Ultra Luxury",
  macan: "Ultra Luxury",
  db11: "Ultra Luxury",
  vantage: "Ultra Luxury",
  "f-type": "Ultra Luxury",
};
export function getCarCategory(model) {
  if (!model) return null;
  const key = model.trim().toLowerCase();
  return CAR_CATEGORY_MAP[key] || null;
}

export { CAR_CATEGORY_MAP };
